### ISSUE TITLE
[Question] Re-assign ejse.data('key') in template?

### ISSUE THREAD

**Issue by iwanowsacha** [bowheart/ejs-electron#19]
I apologize if this is a stupid question but I couldn't figure out if it was possible or not. I was wondering if it's possible to reassign a value ejse.data('key') inside a template? Specifically, inside a script tag (or external script file).

Here's what I would like to do:

```ejs
// template.js
<h1><%= msg %></h1>
<button id="myBtn">Change msg</button>

<script>
document.getElementById('myBtn').addEventListener('click', buttonClick)
function buttonClick() {
  let newMessage = 'new message'
 
  // this is what I want to do
 ejse.data('msg', newMessage)
}
</script>
```

And this is what I've tried so far (inside the script tag, below let newMessage...):
`<% ejse.data('msg', newMessage) %> // newMessage is not defined`

`let a = "<% ejse.data('msg', '" + newMessage + "') %>" // literally assigns + newMessage +, not the variable's value`

`let a = <%= ejse %> // I tried getting the object directly but returns [object Object]`

The only thing I got working is setting the value directly like this: <% ejse.data('msg', 'new message') %> which also updates the h1 tag. However, I need to use a variable because what I'm trying to assign is a dynamic value, not something I can write directly.

I also tried updating the original object in main.js (using ipcMain and ipcRenderer) but the changes are only reflected after a reload.

Hopefully that made sense and again, I apologize if it was a stupid question.

**Comment by bowheart** [comment]
Good question. The README might need to be a little clearer. You clearly found the answer with ipcMain and ipcRenderer, but I'll explain a little more.

Ejs and ejs-electron only run on the back end (the main process). Ejs and ejs-electron do not exist on the front end (renderer process). Only the final output of ejs is sent to renderer processes. When that code gets to the front end, it has no knowledge of how it was generated. When you do `<%= msg %>`, that `msg` expression will be evaluated in the main process. But the code in the `<script>` tag is running in a renderer process. The script therefore can't interact with `ejse`.

In order to change ejs-electron state and re-evaluate the `<%= msg %>` expression, you have to send a request to the back end via ipcRenderer, call `ejse.data('msg', newMessage)` *in the main process*, and then reload the page that renders `template.js`. Looks like you discovered this.

This is not usually desirable UX. Typically, you'll want the page to be interactive by updating the UI using front end JavaScript. Since it's on the front end, ejs and ejs-electron are not involved.

```ts
// template.js
<h1 id="myHeading"><%= msg %></h1>
<button id="myBtn">Change msg</button>

<script>
const heading = document.getElementById('myHeading')

document.getElementById('myBtn').addEventListener('click', buttonClick)
function buttonClick() {
  let newMessage = 'new message'

  heading.innerText = newMessage
}
</script>
```

Manually updating the UI like this can get messy fast though. This is where front end libraries like React and Vue excel. You can get pretty far without them though by keeping local state in the renderer process and re-rendering the UI based on that state. If I had to write front end JavaScript without any view library, I'd probably set it up something like the following:

```ts

// template.js
<h1 id="myHeading"></h1>
<button id="myBtn">Change msg</button>

<script>
let message = '<%= msg %>' // bootstrap the initial state
const heading = document.getElementById('myHeading')

document.getElementById('myBtn').addEventListener('click', buttonClick)

function buttonClick() {
  updateMessage('new message')
}

function updateMessage(newMessage) {
  message = newMessage
  renderMessage()
}

function renderMessage() {
  heading.innerText = message
}

renderMessage() // initial render of the page with the default state (which we bootstrapped from ejs)
</script>
```

obviously overkill for this example, but I've used this `update` and `render` pattern a couple times with great success in situations where I couldn't use a view library.

**Comment by iwanowsacha** [comment]
I understand better how it works now thanks to the explanation and I'll probably follow that example to update the UI without a view library.
Thanks a lot!

**Comment by FabianoLothor** [comment]
I've been using `webContents` events to similar purposes.

```
window.webContents.on("will-frame-navigate", function (event) {
  console.log(event.url);
  // ...
}
```

Usually sending a URL parameter with the action that I want to perform.
