### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by dragantl** [bowheart/ejs-electron#4]
Not that the interceptors seem to work, I get the following error:

```
 "Not allowed to load local resource: file:///C:/Users/.../public/window.ejs", so
urce: data:text/html,chromewebdata (0)
```

My invocation code:

```
window = new BrowserWindow();

window.loadURL('file://' + path.join(global.__publicdir, 'window.ejs'));
```

**Comment by DaltonPelkey** [comment]
I get this same issue. Help would be appreciated.

**Comment by dragon-ryderz** [comment]
I've been trying to reproduce this problem.  The only way I can get that error is if the file I pass to `window.loadUrl()` doesn't exist.  This error is thrown on just the initially requested file (and not any resources requested by that file) regardless of whether `ejs-electron` is loaded/listening or not.  If that's the behavior you guys are experiencing, then this is not related to `ejs-electron`, but a native part of electronJS.

I'd recommend [this Stack Overflow question](http://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page/18246357#18246357) for help working with the `file://` protocol.

It does look like people have had trouble loading absolute file paths over the `file://` protocol due to browser security (see [this electron issue](https://github.com/atom/electron/issues/4612) and [this Stack Overflow question](http://stackoverflow.com/questions/35568293/can-you-use-absolute-paths-in-electron)).  If that's what you are trying to do, and we find that that's a common use case, I can add functionality to `ejs-electron` to register/intercept a custom protocol to work around the browser security issues regarding the `file://` protocol.

**Comment by dragantl** [comment]
Yeah, I was trying to open a local file... didn't try the three slashes.

**Comment by Orfeous** [comment]
same problem for me

**Comment by bowheart** [comment]
Closed since this problem is due to:
1. Incorrect use of the `file://` protocol (make sure you're using 3 slashes or specifying the host when accessing local files)
2. Attempting to access files using the `file://` protocol that chrome won't load due to security reasons (remember that browsers don't like letting the site they're running access the file system of the local OS).

Neither of these problems are currently in the scope of `ejs-electron`
